"""first commit

Revision ID: 2510d6e2cae2
Revises: f5a0bf55ba0a
Create Date: 2024-06-06 17:31:51.155018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2510d6e2cae2'
down_revision = 'f5a0bf55ba0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
